import { Roboto } from 'next/font/google'
import {AppProvider} from "@/components/AppContext"
import './globals.css'
import Header from '../components/layout/Header'
import { Toaster } from 'react-hot-toast'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className="font-poppins">
        <main className='max-width-4xl mx-auto p-4'>
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="mt-16">
  {/* Top thin gray line, shorter than full width */}
  <div className="mx-auto max-w-4xl border-t border-gray-300"></div>

  <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 flex flex-col md:flex-row items-center justify-between">
    
    {/* Left: Logo / Name */}
    <div className="text-gray-900 font-bold text-lg mb-4 md:mb-0">
      Boba Muy Rico
    </div>

    {/* Center: Navigation Links */}
    <div className="flex flex-col md:flex-row items-center space-y-2 md:space-y-0 md:space-x-6 text-gray-700 mb-4 md:mb-0">
      <a href="/menu" className="hover:text-gray-900 transition">
        Order Online
      </a>
      <a href="/about" className="hover:text-gray-900 transition">
        About Us
      </a>
    </div>

    {/* Right: Copyright */}
    <div className="text-gray-500 text-sm">
      &copy; bobamuyrico 2025
    </div>
  </div>
</footer>
          </AppProvider>  
        </main>
      </body>
    </html>
  )
}
